repositoryType: memory

server:
  host: 0.0.0.0
  port: 8080

grpc:
  host: 0.0.0.0
  port: 50051

db:
  host: localhost
  port: 5432
  user: otus
  pass: otus
  name: calendar

logger:
  level: debug
  filePath: logs/calendar.log